language: node_js
node_js:
  - "6"
env:
  - CXX=g++-4.8
addons:
  hosts:
    - test.serandives.com
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
services:
  - mongodb